# Generated by Django 6.0.6 on 2026-06-04 18:06

import decide.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(default=decide.models.generate_join_code, editable=False, max_length=6, unique=True)),
                ('status', models.CharField(choices=[('WRITING', 'Writing'), ('REVIEW', 'Review'), ('RESULT', 'Result')], default='WRITING')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='decide.writer')),
            ],
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewers', to='decide.session')),
            ],
            options={
                'unique_together': {('name', 'session')},
            },
        ),
    ]
