# Generated by Django 6.0.6 on 2026-06-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='writer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='writer',
            name='last_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reviewer',
            unique_together={('first_name', 'last_name', 'session')},
        ),
    ]
