# Generated by Django 6.0.6 on 2026-06-06 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decide', '0002_rename_name_reviewer_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.IntegerField(default=1)),
                ('content', models.CharField()),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='decide.session')),
            ],
        ),
    ]
