# Generated by Django 6.0.6 on 2026-06-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decide', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.CharField(blank=True),
        ),
    ]
