# Generated by Django 6.0.6 on 2026-06-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decide', '0004_alter_document_content'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='writer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_writer'),
        ),
    ]
