# Generated by Django 6.0.6 on 2026-06-07 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decide', '0005_writer_unique_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('reason', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('document_revision_snapshot', models.IntegerField(editable=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='decide.document')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='decide.reviewer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'document', 'document_revision_snapshot'), name='review_per_revision')],
            },
        ),
    ]
